### ISSUE TITLE
Can't show Dev Tools

### ISSUE THREAD

**Issue by Plukers** [aardvark-platform/aardvark.media#11]
AardvarkCefBrowser ShowDevTools() throws this exception

```
Method not found: 'Void Xilium.CefGlue.WindowsForms.CefWebBrowser.add_BrowserCreated(System.EventHandler)'.
```

**Comment by haraldsteinlechner** [comment]
nuget Another.Unofficial.Xilium.CefGlue                          ~> 0.1.0
nuget Another.Unofficial.Xilium.CefGlue.UnpackNativeDependencies ~> 0.1.0
nuget Another.Unofficial.Xilium.CefGlue.WindowsForms             ~> 0.1.0

add this to your paket.dependencies

**Comment by Plukers** [comment]
Works like warm butter, thanks!!
