### ISSUE TITLE
Mapped download does not work on osx AMD PRO 460

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.media#38]
diagnostics and debugging was done here: https://github.com/aardvark-platform/aardvark.templates/issues/2

this one seems to work: https://github.com/aardvark-platform/aardvark.media/blob/8ceadad2f3d810311790fa2d9916cff6780598ba/src/Aardvark.Service/Server.fs#L301

the RawDownloader does not.

Seems like JpegDownloader uses blit in all cases. @hyazinthh something dangerous jumping to your eye?

**Comment by haraldsteinlechner** [comment]
actually it does not work on AMD 560 also @krauthaufen - so a reproducible downloard or mapping problem.

**Comment by haraldsteinlechner** [comment]
Basically 2 solutions:
 - use texture and getTexImage
 - fix pbo approach

Last time we tried to run also texture download tests from rendering on AMD560 - we would now catch up on this to understand the problem - this should be done in any case and is inevitable since other download uploads could as well be affected.
Said that, @hyazinthh implemented option (2) - should be very portable afaik, what you think @krauthaufen  https://github.com/aardvark-platform/aardvark.media/commit/b425bf6864b3a4341d4dfb6add0373c3b537b150

**Comment by hyazinthh** [comment]
I implemented both ways for testing, and "fix pbo approach" basically means not using a PBO at all and writing into host memory directly with `glReadPixels`.

**Comment by haraldsteinlechner** [comment]
did you find any hits what the problem with pbo actually is? pbo is really an old feature ;)

**Comment by hyazinthh** [comment]
No, not at all. Only that PBO + render buffer is a bad idea here. PBO + texture works fine.
