### ISSUE TITLE
unproper \r\n handling of text nodes

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.media#6]

**Comment by krauthaufen** [comment]
Maybe simply encode text as binary in the javascript code? (base64 or similar)
This would prevent future errors when using special characters.

**Comment by haraldsteinlechner** [comment]
https://github.com/aardvark-platform/aardvark.media/commit/322e9d126134d7fb0cb5f3ddac06557df935dd70
