### ISSUE TITLE
Broken image when taking screenshot with mismatching sampling size

### ISSUE THREAD

**Issue by ThomasOrtner** [aardvark-platform/aardvark.media#8]
When taking a screenshot via the screenshot service and the sampling size of the service and the targeted render node / control do not match the screenshot becomes garbage. Refreshing in quick succession returns a valid screeshot, leading to the assumption that the first frame is somehow broken.

**Comment by krauthaufen** [comment]
possibly fixed by 5186a05273fb780dfe29498da06dd7cca0e80cc4

**Comment by haraldsteinlechner** [comment]
@ThomasOrtner please check this

**Comment by haraldsteinlechner** [comment]
should be fixed
